### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by michelbl** [HelloFax/hellosign-nodejs-sdk#111]
A new major version was introduced in September 2021, yet there is no migration guide nor changelog to help migrate to the new version. I could not find that information either in the API reference : https://developers.hellosign.com/

**Comment by ronaldl29** [comment]
I ran into the same thing. Support was unable to give me much information. @michelbl

**Comment by nathanbuchar** [comment]
Hey there! I published this change last year. Although it was technically a major version upgrade, the APIs should be identical to v1. We were forced to do a major version upgrade because the change we introduced removed bluebird as a dependency and used native promises instead. This would have technically broken the integration for users running _very old_ versions of Node (which don't support promises), and because of that we were required to publish as a new major version so as to conform to proper semantic versioning

I apologize if this was not clear. We did not see a reason to introduce an upgrade guide, because, simply, there were no API changes. If it's alright, I'm going to close this ticket, as I believe this comment should resolve all future issues and should serve as an explanation to others with similar questions. But feel free to let me know if you think I should re-open
