### ISSUE TITLE
Invalid parameter: custom_fields

### ISSUE THREAD

**Issue by mehdichik** [HelloFax/hellosign-nodejs-sdk#19]
Hi everyone,
I got this error: `{ statusCode: 400,
I20160811-16:02:10.019(2)?      content: '{"error":{"error_msg":"Invalid parameter: custom_fields","error_name":"bad_request"}}'`  while attempting to create a new draft template with custom fields.

**Comment by npbee** [comment]
Hi @mehdichik.  I realize this issue is quite old now, but I believe the issue here is that `custom_fields` is only a valid parameter when sending a signature request with a template or creating an embedded signature request with a template.  When creating embedded drafts, the `merge_fields` parameter should be used:  https://app.hellosign.com/api/reference#create_embedded_template_draft.  

Please feel free to reopen if you are still having issues.  Thanks!
