### ISSUE TITLE
The allow_reassign parameter does not work on non-embedded endpoints. 

### ISSUE THREAD

**Issue by Framinus** [HelloFax/hellosign-nodejs-sdk#41]
When an embedded signature request is passed the parameter "allow_reassign": true, the signer is able to reassign the signature request in the embedded editor.

However, when passing the same allow_reassign parameter to either the signatureRequest.send() or signatureRequest.sendWithTemplate() methods, the parameter does not get included in the request. I confirmed that is not getting passed in the request logs, and the option to reassign is not available when the signer opens the editor.

**Comment by latoyazamill** [comment]
Hi @Framinus I ran a few tests today and can confirm the following: 

- When a non-embedded signature request is passed the parameter "allow_reassign": 1, the signer is able to reassign the signature request in the embedded editor.
- When an embedded signature request is passed the parameter "allow_reassign": 1, the signer is able to reassign the signature request in the embedded editor.

**However**

- When an embedded signature request with template is passed the parameter "allow_reassign": 1, the signer is not able to reassign the signature request in the embedded editor.
- When a non-embedded signature request with a template is passed the parameter "allow_reassign": 1, the signer is not able to reassign the signature request in the embedded editor.

An error is instead thrown in both of those cases: `Error: Invalid parameter: allow_reassign`

This is because when you create a template on app.hellosign.com you are provided an option to check a box that says, **"Enable signer reassignment."** Checking this box triggers this feature for use. 

When creating an embedded template, use the `allow_reassign` param when the template is initially created to enable that functionality for that particular template. 

**Note:** The **allow_reassign _param_ is not available for use on** the non-embedded and embedded signature request endpoints that use **templates** at this time.

For these reasons, I am now able to close this request.
